import connectDB from "@/lib/db";        // ✅ correct
import Product from "@/models/Product";  // ✅ correct

const getRandomImage = () => `https://picsum.photos/500/300?random=${Math.random()}`;

export async function GET() {
    await connectDB();
    const data = await Product.find();
    await Product.deleteMany();
    await Product.insertMany([
  {
    title: "Running Shoes",
    description: "Lightweight and breathable running shoes for outdoor activities.",
    price: 79.99,
    category: "Footwear",
    image: getRandomImage(),
  },
  {
    title: "Blue Sneakers",
    description: "Comfortable and stylish blue sneakers for everyday wear.",
    price: 59.99,
    category: "Footwear",
    image: getRandomImage(),
  },
  {
    title: "Red T-Shirt",
    description: "Soft and breathable red t-shirt made from 100% cotton.",
    price: 19.99,
    category: "Apparel",
    image: getRandomImage(),
  },
  {
    title: "Wireless Headphones",
    description: "High-quality wireless headphones with noise-cancellation feature.",
    price: 129.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Smart Watch",
    description: "Feature-rich smartwatch with fitness and sleep tracking.",
    price: 149.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Gaming Mouse",
    description: "RGB gaming mouse with programmable buttons.",
    price: 39.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Mechanical Keyboard",
    description: "Mechanical keyboard with tactile switches and RGB lighting.",
    price: 89.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Laptop Backpack",
    description: "Water-resistant backpack with laptop compartment.",
    price: 49.99,
    category: "Accessories",
    image: getRandomImage(),
  },
  {
    title: "Leather Wallet",
    description: "Premium leather wallet with multiple card slots.",
    price: 24.99,
    category: "Accessories",
    image: getRandomImage(),
  },
  {
    title: "Black Hoodie",
    description: "Warm and comfortable hoodie for everyday use.",
    price: 34.99,
    category: "Apparel",
    image: getRandomImage(),
  },
  {
    title: "Denim Jacket",
    description: "Classic denim jacket with a modern fit.",
    price: 54.99,
    category: "Apparel",
    image: getRandomImage(),
  },
  {
    title: "Running Shoes",
    description: "Lightweight running shoes with cushioned soles.",
    price: 79.99,
    category: "Footwear",
    image: getRandomImage(),
  },
  {
    title: "White Sneakers",
    description: "Minimalist white sneakers suitable for all occasions.",
    price: 64.99,
    category: "Footwear",
    image: getRandomImage(),
  },
  {
    title: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with deep bass.",
    price: 69.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Travel Mug",
    description: "Insulated travel mug keeps drinks hot or cold.",
    price: 14.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Coffee Maker",
    description: "Automatic coffee maker with programmable timer.",
    price: 89.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Office Chair",
    description: "Ergonomic office chair with lumbar support.",
    price: 199.99,
    category: "Furniture",
    image: getRandomImage(),
  },
  {
    title: "Study Desk",
    description: "Spacious wooden desk ideal for study and work.",
    price: 149.99,
    category: "Furniture",
    image: getRandomImage(),
  },
  {
    title: "LED Desk Lamp",
    description: "Adjustable LED desk lamp with brightness control.",
    price: 29.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Yoga Mat",
    description: "Non-slip yoga mat suitable for all exercises.",
    price: 24.99,
    category: "Sports",
    image: getRandomImage(),
  },
  {
    title: "Dumbbell Set",
    description: "Adjustable dumbbell set for home workouts.",
    price: 99.99,
    category: "Sports",
    image: getRandomImage(),
  },
  {
    title: "Football",
    description: "Durable football for practice and matches.",
    price: 19.99,
    category: "Sports",
    image: getRandomImage(),
  },
  {
    title: "Basketball",
    description: "Professional-grade basketball with superior grip.",
    price: 29.99,
    category: "Sports",
    image: getRandomImage(),
  },
  {
    title: "Tennis Racket",
    description: "Lightweight tennis racket for beginners and pros.",
    price: 79.99,
    category: "Sports",
    image: getRandomImage(),
  },
  {
    title: "Sunglasses",
    description: "Stylish UV-protected sunglasses.",
    price: 29.99,
    category: "Accessories",
    image: getRandomImage(),
  },
  {
    title: "Baseball Cap",
    description: "Adjustable baseball cap with breathable fabric.",
    price: 16.99,
    category: "Accessories",
    image: getRandomImage(),
  },
  {
    title: "Silver Necklace",
    description: "Elegant silver necklace for daily wear.",
    price: 44.99,
    category: "Jewelry",
    image: getRandomImage(),
  },
  {
    title: "Gold Bracelet",
    description: "Stylish bracelet with premium finish.",
    price: 59.99,
    category: "Jewelry",
    image: getRandomImage(),
  },
  {
    title: "Smartphone Stand",
    description: "Adjustable stand for phones and small tablets.",
    price: 12.99,
    category: "Accessories",
    image: getRandomImage(),
  },
  {
    title: "USB-C Hub",
    description: "Multi-port USB-C hub for laptops and tablets.",
    price: 34.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "External SSD",
    description: "Fast and portable external SSD storage.",
    price: 119.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Monitor 24 Inch",
    description: "Full HD monitor with vivid colors.",
    price: 179.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Wireless Charger",
    description: "Fast wireless charger compatible with most devices.",
    price: 24.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Portable Power Bank",
    description: "10000mAh power bank for charging on the go.",
    price: 29.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Gaming Controller",
    description: "Wireless controller with responsive controls.",
    price: 49.99,
    category: "Gaming",
    image: getRandomImage(),
  },
  {
    title: "Gaming Headset",
    description: "Immersive surround sound gaming headset.",
    price: 69.99,
    category: "Gaming",
    image: getRandomImage(),
  },
  {
    title: "Action Camera",
    description: "Compact action camera for adventures and travel.",
    price: 199.99,
    category: "Electronics",
    image: getRandomImage(),
  },
  {
    title: "Tripod Stand",
    description: "Lightweight tripod stand for cameras and phones.",
    price: 39.99,
    category: "Photography",
    image: getRandomImage(),
  },
  {
    title: "Water Bottle",
    description: "Reusable stainless steel water bottle.",
    price: 18.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Air Fryer",
    description: "Healthy cooking air fryer with digital controls.",
    price: 129.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Electric Kettle",
    description: "Fast-boiling electric kettle with auto shut-off.",
    price: 39.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  },
  {
    title: "Coffee Maker",
    description: "Automatic coffee maker for home brewing.",
    price: 59.99,
    category: "Home & Kitchen",
    image: getRandomImage(),
  }
]);
    return Response.json({message: "Database seeded successfully"});
}